apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/upendrasahu/pythonapp1-10042:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/upendrasahu/pythonapp1-10042:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: pythonapp1-10042
        chartPath: charts/pythonapp1-10042
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/upendrasahu/pythonapp1-10042"
          image.tag: "{{.DIGEST_HEX}}"
